/**
 * Comprehensive K-12 Mathematics Syllabus
 * 8 topics per grade × 12 grades = 96 topics
 * Each topic expands into a full lesson with content, study guide, key terms, examples, and quiz.
 */
export interface SyllabusTopic {
  title: string;
  slug: string;
  summary: string;
  objectives: string[];
  keyTerms: { term: string; definition: string }[];
  keyPoints: string[];
  difficulty: "introductory" | "core" | "advanced";
  durationMin: number;
}
export interface GradeSyllabus { grade: number; topics: SyllabusTopic[]; }

export const MATH_SYLLABUS: GradeSyllabus[] = [
  { grade: 1, topics: [
    { title: "Counting & Place Value to 100", slug: "counting-place-value-100", summary: "Read, write, order and compare numbers up to 100 using tens and ones.", objectives: ["Count forwards and backwards to 100 in ones and tens","Read and write numerals and number words to 100","Partition two-digit numbers into tens and ones","Identify one more and one less than a given number"], keyTerms: [{term:"Digit",definition:"A single symbol 0-9 used to make numbers"},{term:"Tens",definition:"The place value of the second digit from the right"},{term:"Ones",definition:"The place value of the rightmost digit, also called units"},{term:"100-square",definition:"A 10×10 grid showing numbers 1-100 in order"}], keyPoints: ["47 = 4 tens (40) + 7 ones (7)","Compare numbers by looking at the tens digit first","Symbols: < less than, > greater than, = equal to","One more = add 1; one less = subtract 1","Counting by tens moves down a column on the 100-square"], difficulty: "introductory", durationMin: 25 },
    { title: "Addition Within 20", slug: "addition-within-20", summary: "Add single-digit numbers to 20 using counting on and number bonds.", objectives: ["Add two one-digit numbers to totals up to 20","Use counting on from the larger number","Know number bonds to 10 and 20 by heart","Solve simple word problems involving addition"], keyTerms: [{term:"Sum",definition:"The result of adding two or more numbers"},{term:"Number bonds",definition:"Pairs of numbers that add up to a given total"},{term:"Counting on",definition:"Starting at the larger number and counting forward"},{term:"Doubles",definition:"Adding a number to itself, e.g. 5+5=10"}], keyPoints: ["Number bonds to 10: 0+10, 1+9, 2+8, 3+7, 4+6, 5+5","Count on: 7 + 3 → start at 7, count 8, 9, 10","Doubles: 1+1=2, 2+2=4, ..., 10+10=20","Addition is commutative: 3+5 = 5+3","Near doubles: 6+7 = 6+6+1 = 13"], difficulty: "introductory", durationMin: 25 },
    { title: "Subtraction Within 20", slug: "subtraction-within-20", summary: "Subtract within 20 using counting back and number bonds.", objectives: ["Subtract one-digit numbers from numbers up to 20","Use counting back and number bonds","Understand subtraction as taking away and finding the difference","Solve simple word problems"], keyTerms: [{term:"Difference",definition:"The result of subtraction; how far apart two numbers are"},{term:"Minuend",definition:"The number being subtracted from"},{term:"Subtrahend",definition:"The number being subtracted"},{term:"Fact family",definition:"Related addition and subtraction facts using the same numbers"}], keyPoints: ["Subtraction is the inverse of addition: 10-3=7 because 7+3=10","Count back: 10-3 → 9, 8, 7","Finding the difference: 9-5=4","Fact families: 3+5=8, 5+3=8, 8-3=5, 8-5=3","Zero property: any number minus itself is 0"], difficulty: "introductory", durationMin: 25 },
    { title: "2D Shapes & Patterns", slug: "2d-shapes-patterns", summary: "Recognise and name 2D shapes; continue repeating patterns.", objectives: ["Name circle, triangle, square, rectangle, pentagon, hexagon","Describe shapes using sides and corners","Continue repeating patterns","Sort shapes by properties"], keyTerms: [{term:"Side",definition:"A straight edge of a shape"},{term:"Corner/Vertex",definition:"Where two sides meet"},{term:"Polygon",definition:"A closed shape made of straight sides"},{term:"Pattern",definition:"A repeated arrangement of shapes, colours or numbers"}], keyPoints: ["Triangle: 3 sides, 3 corners","Square: 4 equal sides, 4 corners","Rectangle: 4 sides (opposites equal)","Pentagon: 5 sides; Hexagon: 6 sides","Circle: no sides, no corners","Repeating patterns: AB, AAB, ABC, AABB"], difficulty: "introductory", durationMin: 25 },
    { title: "Measurement: Length & Height", slug: "measurement-length-height", summary: "Compare and measure length using standard and non-standard units.", objectives: ["Compare lengths using longer, shorter, taller","Measure using non-standard units","Measure to the nearest centimetre","Solve simple length problems"], keyTerms: [{term:"Length",definition:"How long something is from end to end"},{term:"Height",definition:"How tall something is from bottom to top"},{term:"Centimetre (cm)",definition:"A unit of length, about the width of a fingernail"},{term:"Ruler",definition:"A tool for measuring length"}], keyPoints: ["Start measuring from 0 on the ruler","1 metre = 100 centimetres","Longer/shorter for length; taller/shorter for height","Non-standard units must be same size, end-to-end","Estimate before measuring"], difficulty: "introductory", durationMin: 25 },
    { title: "Time: Days, Months & Clocks", slug: "time-days-months-clocks", summary: "Tell time to the hour and half hour; name days and months.", objectives: ["Tell time to hour and half hour","Name days of the week","Name months of the year","Read o'clock and half past"], keyTerms: [{term:"Hour hand",definition:"The short hand pointing to the hour"},{term:"Minute hand",definition:"The long hand pointing to minutes"},{term:"O'clock",definition:"Minute hand on 12, on the hour"},{term:"Half past",definition:"Minute hand on 6, 30 min past"}], keyPoints: ["7 days in a week: Monday-Sunday","12 months in a year","Minute hand on 12 = o'clock","Minute hand on 6 = half past","24 hours in a day; 60 minutes in an hour"], difficulty: "introductory", durationMin: 25 },
    { title: "Money & Coins", slug: "money-coins", summary: "Recognise coins and notes; make amounts and calculate change.", objectives: ["Recognise and name coins and notes","Match coins to values","Make amounts with different coins","Calculate simple change"], keyTerms: [{term:"Coin",definition:"Metal money"},{term:"Note",definition:"Paper money"},{term:"Value",definition:"How much a coin or note is worth"},{term:"Change",definition:"Money given back when you pay too much"}], keyPoints: ["Coins: 1p, 2p, 5p, 10p, 20p, 50p, £1, £2","Notes: £5, £10, £20, £50","10p = 5p+5p = 2p+2p+2p+2p+2p","Change = amount paid - cost","Count up from cost to amount paid"], difficulty: "introductory", durationMin: 25 },
    { title: "Fractions: Halves & Quarters", slug: "fractions-halves-quarters", summary: "Find halves and quarters of shapes and quantities.", objectives: ["Find half of shapes and quantities","Find quarters of shapes and quantities","Recognise two quarters = one half","Write simple fractions"], keyTerms: [{term:"Half (½)",definition:"One of two equal parts"},{term:"Quarter (¼)",definition:"One of four equal parts"},{term:"Equal parts",definition:"Pieces exactly the same size"},{term:"Numerator",definition:"Top number, how many parts you have"}], keyPoints: ["Half = 2 equal parts, each is ½","Quarter = 4 equal parts, each is ¼","Two quarters = one half: ¼+¼ = ½","Half of 10 = 5; Quarter of 8 = 2","Parts must be EQUAL"], difficulty: "introductory", durationMin: 25 },
  ]},
  { grade: 2, topics: [
    { title: "Numbers to 1000 & Place Value", slug: "numbers-1000-place-value", summary: "Read, write, order numbers to 1000 using hundreds, tens, ones.", objectives: ["Read and write numbers to 1000","Partition three-digit numbers","Compare and order to 1000","Count in 2s, 3s, 5s, 10s"], keyTerms: [{term:"Hundreds",definition:"Third digit from the right"},{term:"Partition",definition:"Splitting a number into place values"},{term:"Expanded form",definition:"342 = 300+40+2"},{term:"Ascending",definition:"Smallest to largest"}], keyPoints: ["342 = 3 hundreds + 4 tens + 2 ones","Compare hundreds first, then tens, then ones","Count in 2s: 2,4,6,8,10...","10 ones = 1 ten; 10 tens = 1 hundred","10 hundreds = 1000"], difficulty: "introductory", durationMin: 30 },
    { title: "Addition & Subtraction to 100", slug: "addition-subtraction-100", summary: "Add and subtract two-digit numbers using column method.", objectives: ["Add two two-digit numbers (column)","Subtract two-digit numbers (column)","Use mental strategies","Solve two-step word problems"], keyTerms: [{term:"Column method",definition:"Writing numbers vertically by place value"},{term:"Exchange/Regroup",definition:"Swapping 10 ones for 1 ten"},{term:"Partitioning",definition:"47+23 = 47+20+3"},{term:"Inverse",definition:"Addition and subtraction are inverse"}], keyPoints: ["Start with ones column","Exchange when column totals 10+","Check: 56-23=33, verify 33+23=56","Mental: 47+23 = 47+20+3 = 70","Rounding: 48+29 ≈ 50+30 = 80, adjust -3 = 77"], difficulty: "core", durationMin: 30 },
    { title: "Multiplication as Repeated Addition", slug: "multiplication-repeated-addition", summary: "Understand multiplication; learn 2, 5, 10 times tables.", objectives: ["Understand multiplication as groups","Know 2, 5, 10 times tables","Use arrays","Solve word problems"], keyTerms: [{term:"Product",definition:"Result of multiplication"},{term:"Array",definition:"Rows and columns showing multiplication"},{term:"Commutative",definition:"3×4 = 4×3"},{term:"Factor",definition:"A number being multiplied"}], keyPoints: ["3×4 = 3 groups of 4 = 4+4+4 = 12","Arrays: 3 rows of 4 = 12","10 times table: add a zero","5 times table: ends in 0 or 5","2 times table: all even","a×b = b×a"], difficulty: "core", durationMin: 30 },
    { title: "Division: Grouping & Sharing", slug: "division-grouping-sharing", summary: "Understand division as sharing and grouping; link to multiplication.", objectives: ["Understand sharing and grouping","Use multiplication facts for division","Understand remainders","Solve division problems"], keyTerms: [{term:"Quotient",definition:"Result of division"},{term:"Dividend",definition:"Number being divided"},{term:"Divisor",definition:"Number you divide by"},{term:"Remainder",definition:"Leftover when not exact"}], keyPoints: ["12÷3 = 4: 12 shared into 3 groups = 4 each","Inverse of multiplication: 12÷3=4 because 4×3=12","Grouping: how many 3s in 12? = 4","Remainder: 13÷3 = 4 r 1","Division is NOT commutative: 12÷3 ≠ 3÷12"], difficulty: "core", durationMin: 30 },
    { title: "3D Shapes & Properties", slug: "3d-shapes-properties", summary: "Recognise 3D shapes; describe faces, edges, vertices.", objectives: ["Name cube, cuboid, sphere, cylinder, cone, pyramid","Count faces, edges, vertices","Identify 2D shapes on 3D faces","Sort 3D shapes"], keyTerms: [{term:"Face",definition:"A flat surface of a 3D shape"},{term:"Edge",definition:"Where two faces meet"},{term:"Vertex/Vertices",definition:"Corner where edges meet"},{term:"Prism",definition:"Same cross-section along its length"}], keyPoints: ["Cube: 6 square faces, 12 edges, 8 vertices","Cuboid: 6 faces, 12 edges, 8 vertices","Sphere: 1 curved face, no edges, no vertices","Cylinder: 2 circles, 1 curved, 2 edges","Cone: 1 circle, 1 curved, 1 vertex"], difficulty: "introductory", durationMin: 30 },
    { title: "Statistics: Tally & Pictograms", slug: "statistics-tally-pictograms", summary: "Collect and interpret data using tally charts and pictograms.", objectives: ["Collect data with tally","Draw and interpret pictograms","Read block diagrams","Answer data questions"], keyTerms: [{term:"Tally",definition:"Counting marks, groups of 5"},{term:"Pictogram",definition:"Chart using pictures for data"},{term:"Key",definition:"What each symbol represents"},{term:"Data",definition:"Collected information"}], keyPoints: ["Tally in 5s: |||| then diagonal","Pictogram key: 🍎 = 2 children","Half symbol = half value","Always include title and key","Most popular = most symbols"], difficulty: "introductory", durationMin: 30 },
    { title: "Fractions of Quantities", slug: "fractions-quantities", summary: "Find ½, ¼, ⅓, ¾ of quantities; recognise equivalents.", objectives: ["Find halves, quarters, thirds","Recognise ½ = 2/4","Count in fractions","Solve fraction problems"], keyTerms: [{term:"Numerator",definition:"Top number, parts you have"},{term:"Denominator",definition:"Bottom number, total parts"},{term:"Third (⅓)",definition:"One of three equal parts"},{term:"Equivalent",definition:"Same value, different form"}], keyPoints: ["½ = divide by 2","⅓ = divide by 3","¼ = divide by 4","¾ = find ¼ then ×3","½ = 2/4 (equivalent)","Must be EQUAL parts"], difficulty: "core", durationMin: 30 },
    { title: "Position, Direction & Turns", slug: "position-direction-turns", summary: "Describe position, direction, turns including clockwise/anticlockwise.", objectives: ["Use left, right, forwards, backwards","Describe whole, half, quarter turns","Understand clockwise/anticlockwise","Follow directions on grid"], keyTerms: [{term:"Clockwise",definition:"Same direction as clock hands"},{term:"Anticlockwise",definition:"Opposite to clock hands"},{term:"Quarter turn",definition:"90° rotation"},{term:"Half turn",definition:"180° rotation"}], keyPoints: ["Right = clockwise; left = anticlockwise","Quarter turn = 90° (12 to 3)","Half turn = 180° (12 to 6)","Full turn = 360° (back to start)","Quarter turn right: North→East"], difficulty: "introductory", durationMin: 25 },
  ]},
  { grade: 3, topics: [
    { title: "Numbers to 10,000 & Roman Numerals", slug: "numbers-10000-roman", summary: "Read, write, order to 10,000; learn Roman numerals to XII.", objectives: ["Read and write to 10,000","Order and compare 4-digit numbers","Round to 10, 100, 1000","Read Roman numerals to XII"], keyTerms: [{term:"Thousands",definition:"Fourth digit from right"},{term:"Rounding",definition:"Simplifying while staying close"},{term:"Roman numerals",definition:"I=1, V=5, X=10"},{term:"Estimate",definition:"Sensible guess using rounding"}], keyPoints: ["4,527 = 4 thousands + 5 hundreds + 2 tens + 7 ones","Round to 10: look at ones (5+ rounds up)","Round to 100: look at tens (50+ rounds up)","Roman: I=1, V=5, X=10; IV=4, VI=6, IX=9","No zero in Roman numerals"], difficulty: "core", durationMin: 30 },
    { title: "Column Addition & Subtraction to 1000", slug: "column-add-sub-1000", summary: "Add and subtract 3-digit numbers with exchanging.", objectives: ["Column addition with exchange","Column subtraction with exchange","Estimate using rounding","Multi-step word problems"], keyTerms: [{term:"Exchange (carry)",definition:"10 in a column → 1 in next"},{term:"Exchange (borrow)",definition:"Too small → borrow from next"},{term:"Formal method",definition:"Standard written method"},{term:"Estimate",definition:"Rough calculation to check"}], keyPoints: ["Align by place value","Start from ones, move left","Carry when column ≥ 10","Borrow when top digit smaller","Check: 347+286 ≈ 300+300 = 600"], difficulty: "core", durationMin: 35 },
    { title: "3, 4 & 8 Times Tables", slug: "3-4-8-times-tables", summary: "Learn 3, 4, 8 times tables; understand relationships.", objectives: ["Recall 3, 4, 8 times tables","Understand 8 = 2×4","Derive new facts","Solve problems"], keyTerms: [{term:"Multiple",definition:"Number in a times table"},{term:"Factor pair",definition:"Two numbers multiplying to a product"},{term:"Distributive law",definition:"7×8 = (7×4)+(7×4)"},{term:"Times table",definition:"List of multiples"}], keyPoints: ["3s: 3,6,9,12,15,18,21,24,27,30,33,36","4s: 4,8,12,16,20,24,28,32,36,40,44,48","8s: 8,16,24,32,40,48,56,64,72,80,88,96","8 = 2×4, so 8×3 = 2×(4×3) = 24","6×7=42 is tricky: use 6×6=36 +6"], difficulty: "core", durationMin: 30 },
    { title: "Fractions: Comparing & Adding", slug: "fractions-comparing-adding", summary: "Compare, order, add fractions with same denominator.", objectives: ["Compare same-denominator fractions","Add/subtract same denominator","Recognise equivalents","Count in tenths"], keyTerms: [{term:"Denominator",definition:"Bottom, total parts"},{term:"Equivalent",definition:"½ = 2/4 = 4/8"},{term:"Tenths",definition:"Denominator 10"},{term:"Simplify",definition:"Reduce to lowest terms"}], keyPoints: ["Same denom: compare numerators (3/7 > 2/7)","Same numer: compare denoms (3/4 > 3/5)","Add: 3/8+2/8 = 5/8 (add nums, keep denom)","Equivalent: × or ÷ both by same number","Tenths connect to decimals"], difficulty: "core", durationMin: 35 },
    { title: "Perimeter of 2D Shapes", slug: "perimeter-2d-shapes", summary: "Measure and calculate perimeter of rectangles and shapes.", objectives: ["Measure perimeter","Calculate perimeter of rectangles/squares","Find missing lengths","Solve perimeter problems"], keyTerms: [{term:"Perimeter",definition:"Distance around the edge"},{term:"Rectangle",definition:"4 sides, 4 right angles, opposites equal"},{term:"Square",definition:"Rectangle with 4 equal sides"},{term:"Composite shape",definition:"Made of joined shapes"}], keyPoints: ["Perimeter = sum of all sides","Square: P = 4×side","Rectangle: P = 2×(l+w)","Units: cm, m, km","Composite: add all outer edges"], difficulty: "core", durationMin: 30 },
    { title: "Time: Digital & Duration", slug: "time-digital-duration", summary: "Tell time to the minute; calculate durations.", objectives: ["Tell time to nearest minute","Read 12h and 24h clocks","Calculate durations","Convert hours/minutes/seconds"], keyTerms: [{term:"AM",definition:"Morning, midnight to noon"},{term:"PM",definition:"Afternoon, noon to midnight"},{term:"24-hour",definition:"00:00 to 23:59"},{term:"Duration",definition:"How long an event lasts"}], keyPoints: ["60 sec = 1 min; 60 min = 1 hour","Each number = 5 minutes","3:45 PM = 15:45 (add 12)","Duration = end − start","Crossing noon: count in parts"], difficulty: "core", durationMin: 30 },
    { title: "Angles & Lines", slug: "angles-lines", summary: "Identify right, acute, obtuse angles; parallel and perpendicular lines.", objectives: ["Identify right angles","Recognise acute/obtuse","Identify horizontal/vertical","Parallel and perpendicular"], keyTerms: [{term:"Right angle",definition:"90°"},{term:"Acute",definition:"Less than 90°"},{term:"Obtuse",definition:"Between 90° and 180°"},{term:"Parallel",definition:"Lines never meeting"}], keyPoints: ["Right angle = 90°","Acute: 0° < angle < 90°","Obtuse: 90° < angle < 180°","Horizontal = left-right; Vertical = up-down","Perpendicular = meet at 90°"], difficulty: "core", durationMin: 30 },
    { title: "Statistics: Bar Charts & Tables", slug: "statistics-bar-charts", summary: "Interpret and present data using bar charts and tables.", objectives: ["Draw and interpret bar charts","Read tables","Solve data problems","Compare data sets"], keyTerms: [{term:"Bar chart",definition:"Bars showing data"},{term:"Axis",definition:"Reference line (x/y)"},{term:"Scale",definition:"Numbering on axis"},{term:"Frequency",definition:"How often something happens"}], keyPoints: ["Bars same width, equal gaps","Check scale (2s, 5s, 10s)","Title and label both axes","Tallest = most popular","Shortest = least popular"], difficulty: "core", durationMin: 30 },
  ]},
  { grade: 4, topics: [
    { title: "Numbers to 100,000 & Negatives", slug: "numbers-100000-negatives", summary: "Read, write, order to 100,000; count through zero.", objectives: ["Read/write to 100,000","Order 5-digit numbers","Count through zero","Interpret negatives"], keyTerms: [{term:"Ten thousands",definition:"Fifth digit"},{term:"Negative",definition:"Less than zero"},{term:"Integer",definition:"Whole number (pos/neg/zero)"},{term:"Number line",definition:"Shows numbers in order"}], keyPoints: ["53,742 = 5×10000 + 3×1000 + 7×100 + 4×10 + 2","Negatives LEFT of zero","−5 colder than −2","−3,−2,−1,0,1,2,3","−5+3 = −2 (move right 3)"], difficulty: "core", durationMin: 35 },
    { title: "All Times Tables to 12×12", slug: "all-times-tables-12", summary: "Consolidate all facts to 12×12; factors and multiples.", objectives: ["Recall all to 12×12","Identify factors and factor pairs","Identify multiples","Solve problems"], keyTerms: [{term:"Factor",definition:"Divides exactly into a number"},{term:"Multiple",definition:"Number in a times table"},{term:"Prime",definition:"Exactly 2 factors: 1 and itself"},{term:"Composite",definition:"More than 2 factors"}], keyPoints: ["Factors of 12: 1,2,3,4,6,12","Multiples of 5: 5,10,15,20...","Primes to 20: 2,3,5,7,11,13,17,19","1 is NOT prime","2 is only even prime","Tricky: 6×7=42, 7×8=56, 9×7=63"], difficulty: "core", durationMin: 35 },
    { title: "Formal Methods: Multiply & Divide", slug: "formal-methods-mult-div", summary: "Multiply 2-digit by 2-digit; divide 3-digit by 1-digit.", objectives: ["Grid/long multiplication","Short division","Interpret remainders","Estimate products/quotients"], keyTerms: [{term:"Short multiplication",definition:"2-3 digit × 1 digit"},{term:"Long multiplication",definition:"Two multi-digit numbers"},{term:"Short division",definition:"Bus stop method"},{term:"Remainder",definition:"Leftover in division"}], keyPoints: ["Grid: 34×23 = (30+4)×(20+3) = 600+90+80+12 = 782","Long: multiply by ones, then tens (add 0), add","Short division: divide each digit L→R","72÷5 = 14 r 2","Context: 72 sweets in bags of 5 → 14 bags, 2 left"], difficulty: "core", durationMin: 40 },
    { title: "Area & Perimeter of Rectangles", slug: "area-perimeter-rectangles", summary: "Calculate area by counting and formula; distinguish from perimeter.", objectives: ["Area by counting squares","Area = l×w","Estimate irregular areas","Distinguish area vs perimeter"], keyTerms: [{term:"Area",definition:"Space inside 2D shape"},{term:"cm²",definition:"Square centimetre"},{term:"Formula",definition:"A = l × w"},{term:"Square units",definition:"cm², m²"}], keyPoints: ["Area = length × width","Square: A = side²","Measured in SQUARE units","Perimeter = OUTSIDE; Area = INSIDE","Same area, different perimeters possible"], difficulty: "core", durationMin: 35 },
    { title: "Decimals: Tenths & Hundredths", slug: "decimals-tenths-hundredths", summary: "Understand tenths/hundredths; divide by 10 and 100.", objectives: ["Recognise tenths/hundredths","Divide by 10, 100","Round to whole","Compare to 2 dp"], keyTerms: [{term:"Decimal point",definition:"Separates whole and fraction"},{term:"Tenth (0.1)",definition:"1/10"},{term:"Hundredth (0.01)",definition:"1/100"},{term:"Decimal place",definition:"Position after decimal point"}], keyPoints: ["0.3 = 3/10","0.07 = 7/100","÷10: move right 1 place (35÷10=3.5)","÷100: move right 2 places (35÷100=0.35)","Compare: 0.4 > 0.35 (tenths first)"], difficulty: "core", durationMin: 35 },
    { title: "Symmetry & Shape Properties", slug: "symmetry-shape-properties", summary: "Lines of symmetry; classify triangles and quadrilaterals.", objectives: ["Identify lines of symmetry","Complete symmetrical figures","Classify triangles","Classify quadrilaterals"], keyTerms: [{term:"Line of symmetry",definition:"Mirror line dividing shape"},{term:"Equilateral",definition:"All sides/angles equal"},{term:"Isosceles",definition:"Two equal sides/angles"},{term:"Parallelogram",definition:"Opposite sides parallel/equal"}], keyPoints: ["Square: 4 lines of symmetry","Rectangle: 2 lines","Equilateral triangle: 3 lines","Isosceles: 1 line","Scalene: 0 lines","Regular = all equal"], difficulty: "core", durationMin: 35 },
    { title: "Coordinates & Translation", slug: "coordinates-translation", summary: "Plot coordinates; translate points and shapes.", objectives: ["Read/plot first quadrant","Describe translations","Plot polygons","Use coordinates"], keyTerms: [{term:"Coordinates (x,y)",definition:"Locate a point"},{term:"x-axis",definition:"Horizontal"},{term:"y-axis",definition:"Vertical"},{term:"Translation",definition:"Move without rotating"}], keyPoints: ["(x,y): along corridor, up stairs","Origin = (0,0)","(3,4): 3 right, 4 up","Translate (2,−1): 2 right, 1 down","Shape unchanged in translation"], difficulty: "core", durationMin: 35 },
    { title: "Units & Conversions", slug: "units-conversions", summary: "Convert between length, mass, capacity units.", objectives: ["Convert km/m/cm/mm","Convert kg/g","Convert L/ml","Solve measurement problems"], keyTerms: [{term:"Kilo-",definition:"1000"},{term:"Centi-",definition:"1/100"},{term:"Milli-",definition:"1/1000"},{term:"Mass",definition:"Matter in object (g, kg)"}], keyPoints: ["1 km = 1000 m; 1 m = 100 cm; 1 cm = 10 mm","1 kg = 1000 g","1 L = 1000 ml","km→m: ×1000","m→cm: ×100","cm→mm: ×10"], difficulty: "core", durationMin: 35 },
  ]},
  { grade: 5, topics: [
    { title: "Place Value to 1,000,000 & Rounding", slug: "place-value-million", summary: "Numbers to 1M; round to any power of 10.", objectives: ["Read/write to 1,000,000","Round to 10/100/1000/10000/100000","Interpret negatives","Count in powers of 10"], keyTerms: [{term:"Millions",definition:"7th digit"},{term:"Power of 10",definition:"10,100,1000..."},{term:"Interval",definition:"Gap on a scale"},{term:"Approximation",definition:"Close estimate"}], keyPoints: ["1,000,000 = 10⁶","Round to 1000: look at hundreds","−3°C below freezing","Count in 100,000s: 100k, 200k...","10⁰=1, 10¹=10, 10²=100"], difficulty: "core", durationMin: 35 },
    { title: "Multiplying & Dividing by 10, 100, 1000", slug: "mult-div-powers-10", summary: "Multiply/divide whole and decimal numbers by 10, 100, 1000.", objectives: ["×10/100/1000 integers and decimals","÷10/100/1000","Place value effects","Scaling problems"], keyTerms: [{term:"Scaling",definition:"Making bigger/smaller"},{term:"Place value shift",definition:"Digits move L (×) or R (÷)"},{term:"Placeholder zero",definition:"Zeros holding place value"},{term:"Exponent",definition:"Power raised to"}], keyPoints: ["×10: LEFT 1 place (3.4×10=34)","×100: LEFT 2 places (3.4×100=340)","÷10: RIGHT 1 place (34÷10=3.4)","÷100: RIGHT 2 places (340÷100=3.4)","Count zeros = places moved"], difficulty: "core", durationMin: 30 },
    { title: "Long Multiplication & Division", slug: "long-mult-div", summary: "4-digit × 2-digit; 4-digit ÷ 2-digit long methods.", objectives: ["Long multiplication","Long division","Remainders as fractions/decimals","Estimate to check"], keyTerms: [{term:"Long multiplication",definition:"Written method for larger numbers"},{term:"Long division",definition:"Step-by-step division"},{term:"Partial product",definition:"Result of one digit multiplication"},{term:"Quotient",definition:"Division result"}], keyPoints: ["2345×67: 2345×7 + 2345×60","Long division: divide, multiply, subtract, bring down","17÷3 = 5 r 2 = 5⅔","Check: 2345×67 ≈ 2300×70 = 161,000"], difficulty: "core", durationMin: 40 },
    { title: "Fractions: Adding & Mixed Numbers", slug: "fractions-adding-mixed", summary: "Add/subtract different denominators; mixed numbers.", objectives: ["Different denominator add/subtract","Mixed ↔ improper","Find common denominators","Fraction word problems"], keyTerms: [{term:"Mixed number",definition:"2⅓"},{term:"Improper",definition:"7/3"},{term:"Common denominator",definition:"Shared denominator"},{term:"Simplify",definition:"Lowest terms"}], keyPoints: ["⅓+¼ = 4/12+3/12 = 7/12 (LCM=12)","2⅓ = 7/3 (mixed→improper)","7/3 = 2⅓ (improper→mixed)","Simplify: ÷ by HCF"], difficulty: "core", durationMin: 40 },
    { title: "Decimals: Compare, Order, Round", slug: "decimals-compare-round", summary: "Compare/order to 3 dp; round; convert fractions↔decimals.", objectives: ["Compare to 3 dp","Round to whole/1 dp/2 dp","Convert decimals↔fractions","Order decimals"], keyTerms: [{term:"Thousandth",definition:"0.001, third decimal place"},{term:"Trailing zeros",definition:"0.5 = 0.50"},{term:"Recurring",definition:"0.333... = ⅓"},{term:"Equivalent decimals",definition:"0.5 = 0.50 = 0.500"}], keyPoints: ["0.45 > 0.4 (compare hundredths)","0.3 = 0.30 = 0.300","Round 3.47 to whole = 3","Round 3.47 to 1 dp = 3.5","0.25 = ¼"], difficulty: "core", durationMin: 35 },
    { title: "Percentages", slug: "percentages", summary: "Understand %; find % of amounts; convert fractions/decimals/%.", objectives: ["Percentage as parts per 100","Find 50/25/10/1% of amounts","Convert FDP","Percentage problems"], keyTerms: [{term:"Percent (%)",definition:"Per 100"},{term:"Equivalent",definition:"50% = 0.5 = ½"},{term:"Quantity",definition:"Amount"},{term:"Rate",definition:"Ratio comparing quantities"}], keyPoints: ["50% = ½ = 0.5","25% = ¼ = 0.25","10% = 1/10 = 0.1","1% = 1/100 = 0.01","20% = find 10% then ×2","15% = 10% + 5%"], difficulty: "core", durationMin: 35 },
    { title: "Area: Compound & Triangles", slug: "area-compound-triangles", summary: "Area of compound shapes; estimate triangle area.", objectives: ["Compound rectilinear area","Estimate irregular areas","Triangle area = ½bh","Area problems"], keyTerms: [{term:"Compound shape",definition:"Joined shapes"},{term:"Rectilinear",definition:"Straight sides, right angles"},{term:"Base",definition:"Bottom side"},{term:"Perpendicular height",definition:"90° to base"}], keyPoints: ["Split compound into rectangles","Triangle = ½ × base × height","Count squares for irregular","Same shape, different splits = same area"], difficulty: "core", durationMin: 40 },
    { title: "Volume & Capacity", slug: "volume-capacity", summary: "Volume of cuboids; relate to capacity.", objectives: ["Volume in cm³/m³","Cuboid V = l×w×h","1 cm³ = 1 ml","Volume problems"], keyTerms: [{term:"Volume",definition:"3D space inside solid"},{term:"cm³",definition:"Cube with 1cm sides"},{term:"Cuboid",definition:"Box with 6 rectangular faces"},{term:"Capacity",definition:"How much liquid held"}], keyPoints: ["V = l×w×h","3×2×4 cuboid = 24 cm³","1 cm³ = 1 ml","1 L = 1000 cm³","Units always cubed"], difficulty: "core", durationMin: 35 },
  ]},
  { grade: 6, topics: [
    { title: "Numbers to 10 Million", slug: "numbers-10-million", summary: "Read, write, order to 10M; negative numbers.", objectives: ["Read/write to 10,000,000","Order 7-digit numbers","Intervals across zero","Round to any accuracy"], keyTerms: [{term:"Ten millions",definition:"8th place value"},{term:"Degree of accuracy",definition:"How precise rounding is"},{term:"Integer",definition:"Whole number"},{term:"Interval",definition:"Gap on scale"}], keyPoints: ["10,000,000 = ten million","−5 to 3: distance 8","Round 4,567,832 to 100k → 4,600,000","Compare millions first, then hundred-thousands"], difficulty: "core", durationMin: 35 },
    { title: "Prime Factors, HCF & LCM", slug: "prime-factors-hcf-lcm", summary: "Prime factorisation; HCF and LCM.", objectives: ["Products of prime factors","Find HCF","Find LCM","Solve HCF/LCM problems"], keyTerms: [{term:"Prime factor",definition:"Prime dividing a number"},{term:"HCF",definition:"Highest Common Factor"},{term:"LCM",definition:"Lowest Common Multiple"},{term:"Product of primes",definition:"Number as prime multiplication"}], keyPoints: ["12 = 2²×3","HCF(12,18): factors 12={1,2,3,4,6,12}, 18={1,2,3,6,9,18} → HCF=6","LCM(4,6): mult 4={4,8,12...}, mult 6={6,12...} → LCM=12","Venn diagram: common primes in overlap","HCF × LCM = product of numbers"], difficulty: "advanced", durationMin: 40 },
    { title: "Four Operations with Fractions", slug: "four-ops-fractions", summary: "Add, subtract, multiply, divide fractions.", objectives: ["Add/subtract mixed numbers","Multiply fractions","Divide by whole numbers","Mixed problems"], keyTerms: [{term:"Reciprocal",definition:"¾ → 4/3"},{term:"Improper",definition:"7/4"},{term:"Simplify",definition:"Lowest terms"},{term:"Mixed number",definition:"3½"}], keyPoints: ["Add: common denom first — ⅓+¼ = 4/12+3/12 = 7/12","Multiply: × numerators, × denominators — ⅔×¾ = 6/12 = ½","Divide: × reciprocal — ⅔÷4 = ⅔×¼ = 2/12 = 1/6","3½ = 7/2","Always simplify"], difficulty: "advanced", durationMin: 40 },
    { title: "FDP Conversion", slug: "fdp-conversion", summary: "Convert fluently between fractions, decimals, percentages.", objectives: ["Fraction→decimal/%","Decimal→fraction/%","Order FDP","Mixed problems"], keyTerms: [{term:"Equivalence",definition:"Equal in different forms"},{term:"Terminating",definition:"0.25 (ends)"},{term:"Recurring",definition:"0.333..."},{term:"% increase/decrease",definition:"Growth/shrink as %"}], keyPoints: ["½=0.5=50%","¼=0.25=25%","⅓=0.333...=33⅓%","⅕=0.2=20%","F→D: divide; D→%: ×100"], difficulty: "core", durationMin: 35 },
    { title: "Ratio & Proportion", slug: "ratio-proportion", summary: "Understand ratio; solve proportion and scaling problems.", objectives: ["Ratio comparing parts","Share in a ratio","Scale factors","Proportion problems"], keyTerms: [{term:"Ratio",definition:"Comparing parts 2:3"},{term:"Proportion",definition:"Part-to-whole"},{term:"Scale factor",definition:"Multiplier for scaling"},{term:"Equivalent ratio",definition:"2:3 = 4:6 = 6:9"}], keyPoints: ["2:3 = for every 2 of one, 3 of other","Share 50 in 2:3 → 5 parts, each 10 → 20 and 30","Scale factor 3: × all sides by 3","Direct proportion: 3 cakes $6 → 5 cakes $10","Simplify: 6:9 → 2:3"], difficulty: "core", durationMin: 40 },
    { title: "Algebra: Expressions & Equations", slug: "algebra-expressions-equations", summary: "Letters for unknowns; form expressions; solve equations.", objectives: ["Letters for unknowns","Form expressions","Solve 1-step/2-step equations","Linear sequences"], keyTerms: [{term:"Variable",definition:"Letter for unknown"},{term:"Expression",definition:"3x + 2"},{term:"Equation",definition:"3x + 2 = 11"},{term:"Coefficient",definition:"Number × variable"}], keyPoints: ["3x+2: 3 times x plus 2","Solve 3x+2=11: −2→3x=9→÷3→x=3","Inverse: undo + with −, × with ÷","Sequence 2,5,8,11: 3n−1","Same to both sides"], difficulty: "advanced", durationMin: 40 },
    { title: "Area: Triangles & Parallelograms", slug: "area-triangles-parallelograms", summary: "Area formulas for triangles and parallelograms.", objectives: ["Triangle: ½bh","Parallelogram: bh","Find missing dimensions","Composite areas"], keyTerms: [{term:"Perpendicular height",definition:"90° to base"},{term:"Parallelogram",definition:"Opposite sides parallel/equal"},{term:"Formula",definition:"A = ½ × b × h"},{term:"Base",definition:"Side ⊥ to height"}], keyPoints: ["Triangle = ½ × base × ⊥ height","Parallelogram = base × ⊥ height (NOT slant)","Triangle = half parallelogram (same base/height)","A = ½×6×4 = 12 cm²","A = 6×4 = 24 cm² (parallelogram)"], difficulty: "advanced", durationMin: 35 },
    { title: "Mean, Median, Mode & Range", slug: "mean-median-mode-range", summary: "Calculate averages and range; choose appropriate average.", objectives: ["Calculate mean","Find median","Find mode","Calculate range"], keyTerms: [{term:"Mean",definition:"Sum ÷ count"},{term:"Median",definition:"Middle value"},{term:"Mode",definition:"Most common"},{term:"Range",definition:"Max − min"}], keyPoints: ["3,5,7,8,12: Mean = 35÷5 = 7","Median = 7 (middle of 5)","Mode = most frequent","Range = 12−3 = 9","Even count: median = mean of 2 middle"], difficulty: "core", durationMin: 35 },
  ]},
  { grade: 7, topics: [
    { title: "Integers, BIDMAS & Roots", slug: "integers-bidmas-roots", summary: "Negative integers; order of operations; squares, cubes, roots.", objectives: ["Four operations with integers","Apply BIDMAS","Squares, cubes, roots","Indices notation"], keyTerms: [{term:"BIDMAS",definition:"Brackets, Indices, Div/Mult, Add/Sub"},{term:"Square",definition:"n² = n×n"},{term:"Cube",definition:"n³ = n×n×n"},{term:"Square root (√)",definition:"√9 = 3"}], keyPoints: ["−3×−4 = +12 (neg×neg=pos)","−3×4 = −12","BIDMAS: 3+4×2 = 11 (not 14)","3²=9, 3³=27, √16=4, ∛27=3","Squares: 1,4,9,16,25,36,49,64,81,100"], difficulty: "core", durationMin: 40 },
    { title: "Factors, Primes & Standard Form", slug: "factors-primes-standard-form", summary: "HCF/LCM via primes; standard form.", objectives: ["Products of primes","HCF/LCM via Venn","Standard form","Large number problems"], keyTerms: [{term:"Standard form",definition:"A×10ⁿ, 1≤A<10"},{term:"Index notation",definition:"2³ = 8"},{term:"Prime factorisation",definition:"Product of primes"},{term:"Venn diagram",definition:"Overlapping sets"}], keyPoints: ["60 = 2²×3×5","HCF(60,84): 60=2²×3×5, 84=2²×3×7 → 12","LCM(60,84) = 2²×3×5×7 = 420","35000 = 3.5×10⁴","0.00042 = 4.2×10⁻⁴"], difficulty: "core", durationMin: 40 },
    { title: "FDP & Percentage Change", slug: "fdp-percentage-change", summary: "Convert FDP; percentage increase/decrease; reverse %.", objectives: ["Convert FDP","% increase/decrease","Reverse %","Express as %"], keyTerms: [{term:"% change",definition:"Change as % of original"},{term:"Reverse %",definition:"Find original before change"},{term:"Multiplier",definition:"1.15 for 15% up, 0.85 for down"},{term:"Original value",definition:"Starting amount"}], keyPoints: ["15% up: ×1.15","15% down: ×0.85","After 20% up, $60 → original = 60÷1.2 = $50","3/8 = 0.375","15% of 80 = 12"], difficulty: "core", durationMin: 40 },
    { title: "Algebra: Simplify & Substitute", slug: "algebra-simplify-substitute", summary: "Simplify expressions; expand brackets; substitute.", objectives: ["Collect like terms","Expand brackets","Substitute values","Factorise"], keyTerms: [{term:"Like terms",definition:"Same variables/powers"},{term:"Expand",definition:"3(x+2) = 3x+6"},{term:"Factorise",definition:"3x+6 = 3(x+2)"},{term:"Substitute",definition:"Replace variable with number"}], keyPoints: ["3x+5x = 8x","3x and 5y NOT like terms","4(x+3) = 4x+12","(x+2)(x+3) = x²+5x+6","x=5 in 3x+2: 17"], difficulty: "core", durationMin: 40 },
    { title: "Solving Linear Equations", slug: "solving-linear-equations", summary: "Solve equations including unknowns both sides.", objectives: ["1-step/2-step equations","Unknowns both sides","Brackets","Word → equation"], keyTerms: [{term:"Linear equation",definition:"No powers > 1"},{term:"Balance method",definition:"Same to both sides"},{term:"Inverse",definition:"Opposite operation"},{term:"Solution",definition:"Value making it true"}], keyPoints: ["3x+5=17: −5→3x=12→÷3→x=4","5x−3=2x+9: −2x→3x−3=9→+3→3x=12→x=4","3(x+4)=18: 3x+12=18→3x=6→x=2","Check: substitute back","Same to BOTH sides"], difficulty: "core", durationMin: 40 },
    { title: "Angles in Polygons & Lines", slug: "angles-polygons-lines", summary: "Triangle/quadrilateral/polygon angles; parallel line rules.", objectives: ["Triangle/quadrilateral angles","Polygon interior/exterior","Alternate/corresponding","Angle reasoning"], keyTerms: [{term:"Interior angle",definition:"Inside polygon"},{term:"Exterior angle",definition:"Side + extended next side"},{term:"Alternate",definition:"Z-shape, equal"},{term:"Corresponding",definition:"F-shape, equal"}], keyPoints: ["Triangle = 180°","Quadrilateral = 360°","n-gon interior sum = (n−2)×180°","Regular hexagon interior = 120°","Parallel: alt=, corr=, co-int=180°"], difficulty: "core", durationMin: 40 },
    { title: "Perimeter, Area & Volume", slug: "perimeter-area-volume-7", summary: "Composite shapes; prism volume/surface area.", objectives: ["Composite area/perimeter","Prism volume","Surface area","Unit conversion"], keyTerms: [{term:"Prism",definition:"Same cross-section"},{term:"Surface area",definition:"Total of all faces"},{term:"Cross-section",definition:"Face when sliced"},{term:"Composite",definition:"Joined shapes"}], keyPoints: ["V(prism) = cross-section × length","V(cuboid) = l×w×h","SA(cuboid) = 2(lw+lh+wh)","1 m² = 10,000 cm²","1 m³ = 1,000,000 cm³"], difficulty: "core", durationMin: 40 },
    { title: "Coordinates & Linear Graphs", slug: "coordinates-linear-graphs", summary: "Four quadrants; y=mx+c; gradients.", objectives: ["Plot 4 quadrants","Draw y=mx+c","Find gradient","Equation from graph"], keyTerms: [{term:"Gradient",definition:"Steepness = Δy/Δx"},{term:"y-intercept",definition:"Crosses y-axis"},{term:"Quadrant",definition:"4 regions"},{term:"Linear graph",definition:"Straight line"}], keyPoints: ["y=mx+c: m=gradient, c=y-intercept","Gradient = (y₂−y₁)/(x₂−x₁)","y=2x+3: gradient 2, intercept 3","Plot (0,3),(1,5),(2,7)","Quadrants: I(+,+), II(−,+), III(−,−), IV(+,−)"], difficulty: "core", durationMin: 40 },
  ]},
  { grade: 8, topics: [
    { title: "Indices, Standard Form & Surds", slug: "indices-standard-form-surds", summary: "Index laws; standard form calculations; surds.", objectives: ["Index laws","Standard form calculations","Estimate roots","Simplify surds"], keyTerms: [{term:"Index law",definition:"aᵐ×aⁿ = aᵐ⁺ⁿ"},{term:"Surds",definition:"√2, √3 (irrational)"},{term:"Rationalise",definition:"Remove surds from denominator"},{term:"Negative index",definition:"a⁻ⁿ = 1/aⁿ"}], keyPoints: ["aᵐ×aⁿ = aᵐ⁺ⁿ","aᵐ÷aⁿ = aᵐ⁻ⁿ","(aᵐ)ⁿ = aᵐⁿ","a⁰ = 1","√12 = √(4×3) = 2√3"], difficulty: "advanced", durationMin: 40 },
    { title: "Rounding, Bounds & Errors", slug: "rounding-bounds-errors", summary: "Significant figures; upper/lower bounds; error intervals.", objectives: ["Round to sf and dp","Upper/lower bounds","Error intervals","Bounds problems"], keyTerms: [{term:"Significant figure",definition:"Digits carrying meaning"},{term:"Upper bound",definition:"Highest possible value"},{term:"Lower bound",definition:"Lowest possible value"},{term:"Error interval",definition:"Range of possible values"}], keyPoints: ["3.4769 to 3 sf = 3.48","0.00456 to 2 sf = 0.0046","x=5.4 (1dp): 5.35 ≤ x < 5.45","UB of 5.4+3.2: 5.45+3.25 = 8.7","LB of 5.4×3.2: 5.35×3.15"], difficulty: "advanced", durationMin: 40 },
    { title: "Algebra: Expand, Factorise, Subject", slug: "algebra-expand-factorise-subject", summary: "Double brackets; factorise quadratics; change subject.", objectives: ["Expand double brackets","Factorise quadratics","Change subject","Algebraic fractions"], keyTerms: [{term:"Quadratic",definition:"ax²+bx+c"},{term:"Subject",definition:"Variable on its own"},{term:"FOIL",definition:"First, Outer, Inner, Last"},{term:"Difference of squares",definition:"a²−b² = (a+b)(a−b)"}], keyPoints: ["(x+3)(x+4) = x²+7x+12","(x+5)² = x²+10x+25","x²−9 = (x+3)(x−3)","x²+7x+12 = (x+3)(x+4)","v=u+at → u = v−at"], difficulty: "advanced", durationMin: 40 },
    { title: "Equations & Inequalities", slug: "equations-inequalities", summary: "Fraction equations; inequalities; simultaneous.", objectives: ["Fraction/bracket equations","Linear inequalities","Number lines","Simultaneous (elimination)"], keyTerms: [{term:"Inequality",definition:"<, >, ≤, ≥"},{term:"Simultaneous",definition:"2 equations, 2 unknowns"},{term:"Elimination",definition:"Add/subtract to eliminate"},{term:"Solution set",definition:"All values satisfying"}], keyPoints: ["(x+3)/4=5: ×4→x+3=20→x=17","3x−7<8: +7→3x<15→x<5","−2x<6: REVERSE → x>−3","2x+y=10, 3x−y=5: add→5x=15→x=3,y=4","< = open circle, ≤ = filled"], difficulty: "advanced", durationMin: 40 },
    { title: "Straight Lines: y=mx+c", slug: "straight-lines-ymxc", summary: "Draw/interpret; find equations; parallel/perpendicular.", objectives: ["Draw from y=mx+c","Gradient/intercept from equation","Equation from 2 points","Parallel/perpendicular"], keyTerms: [{term:"Gradient (m)",definition:"Δy/Δx"},{term:"Parallel",definition:"Same gradient"},{term:"Perpendicular",definition:"90°, m₁×m₂=−1"},{term:"Point-slope",definition:"y−y₁=m(x−x₁)"}], keyPoints: ["y=3x−2: gradient 3, intercept −2","Parallel = same gradient","Perpendicular: m₁×m₂ = −1","Gradient (1,2) to (4,8) = 6/3 = 2","Through (1,2) grad 2: y−2=2(x−1)→y=2x"], difficulty: "advanced", durationMin: 40 },
    { title: "Transformations", slug: "transformations-8", summary: "Translate, rotate, reflect, enlarge; describe fully.", objectives: ["Translate by vector","Rotate","Reflect (incl y=x)","Enlarge"], keyTerms: [{term:"Translation",definition:"Move by (a,b)"},{term:"Rotation",definition:"Turn about point"},{term:"Reflection",definition:"Flip over line"},{term:"Enlargement",definition:"Scale from centre"}], keyPoints: ["Translation (3,−2): 3 right, 2 down","Rotation: centre, angle, direction","Reflection: state mirror line","Enlargement SF 2: sides double, area ×4","Negative SF: flips + scales"], difficulty: "core", durationMin: 40 },
    { title: "Pythagoras' Theorem", slug: "pythagoras-theorem", summary: "a²+b²=c² in right-angled triangles.", objectives: ["Apply Pythagoras","Find hypotenuse","Find shorter side","Real-world"], keyTerms: [{term:"Hypotenuse",definition:"Longest side, opposite 90°"},{term:"Right angle",definition:"90°"},{term:"Pythagoras",definition:"a²+b²=c²"},{term:"Converse",definition:"If a²+b²=c² then right-angled"}], keyPoints: ["a²+b²=c² (c=hypotenuse)","3²+4²=25→c=5","5²−3²=16→b=4","Identify hypotenuse first","3,4,5 and 5,12,13 are Pythagorean triples"], difficulty: "core", durationMin: 40 },
    { title: "Probability & Tree Diagrams", slug: "probability-tree-diagrams", summary: "Single/combined events; tree diagrams; sample spaces.", objectives: ["Single event probability","Sample spaces","Tree diagrams","Mutually exclusive/independent"], keyTerms: [{term:"Probability",definition:"0 to 1"},{term:"Mutually exclusive",definition:"Can't both happen"},{term:"Independent",definition:"One doesn't affect other"},{term:"Sample space",definition:"All outcomes"}], keyPoints: ["P = favourable/total","P(not A) = 1−P(A)","Exclusive: P(A or B) = P(A)+P(B)","Independent: P(A and B) = P(A)×P(B)","Tree: multiply along, add between"], difficulty: "core", durationMin: 40 },
  ]},
  { grade: 9, topics: [
    { title: "Quadratic Equations & Parabola", slug: "quadratic-equations-parabola", summary: "Factorise, formula, completing square; sketch.", objectives: ["Solve by factorisation","Quadratic formula","Complete the square","Sketch y=ax²+bx+c"], keyTerms: [{term:"Quadratic",definition:"ax²+bx+c=0"},{term:"Discriminant",definition:"b²−4ac"},{term:"Vertex",definition:"Turning point"},{term:"Root",definition:"Where y=0"}], keyPoints: ["x²+5x+6=(x+2)(x+3)→x=−2 or −3","x=(−b±√(b²−4ac))/2a","Δ>0: 2 roots; Δ=0: 1; Δ<0: none","x²+6x+4=(x+3)²−5; vertex(−3,−5)","Sketch: y-int, roots, vertex"], difficulty: "advanced", durationMin: 50 },
    { title: "Right-Angled Trigonometry", slug: "right-angled-trig", summary: "SOH CAH TOA; find sides and angles.", objectives: ["SOH CAH TOA find sides","Inverse trig for angles","Elevation/depression","3D problems"], keyTerms: [{term:"sin",definition:"opposite/hypotenuse"},{term:"cos",definition:"adjacent/hypotenuse"},{term:"tan",definition:"opposite/adjacent"},{term:"Elevation",definition:"Angle looking up"}], keyPoints: ["SOH: sin θ=O/H","CAH: cos θ=A/H","TOA: tan θ=O/A","O=3,H=5→sin θ=0.6→θ≈36.9°","θ=40°,O=5→A=5/tan40°≈5.96"], difficulty: "advanced", durationMin: 50 },
    { title: "Surds & Indices", slug: "surds-indices-9", summary: "Simplify surds; rationalise; fractional/negative indices.", objectives: ["Simplify surds","Rationalise denominators","Fractional/negative indices","Solve index/surd equations"], keyTerms: [{term:"Surd",definition:"√2 (irrational)"},{term:"Rationalise",definition:"Remove surds from denominator"},{term:"Fractional index",definition:"a^(1/n) = ⁿ√a"},{term:"Conjugate",definition:"a+√b and a−√b"}], keyPoints: ["√12=2√3","√3×√3=3","√3×√5=√15","1/√3 × √3/√3 = √3/3","27^(2/3)=9","a^(−1)=1/a"], difficulty: "advanced", durationMin: 45 },
    { title: "Simultaneous Equations & Inequalities", slug: "simultaneous-inequalities", summary: "Linear/quadratic simultaneous; graph inequalities.", objectives: ["Linear simultaneous","Quadratic simultaneous","Linear inequalities","Quadratic inequalities"], keyTerms: [{term:"Elimination",definition:"Add/subtract equations"},{term:"Substitution",definition:"Rearrange + substitute"},{term:"Quadratic inequality",definition:"x²−4<0"},{term:"Region",definition:"Area satisfying inequality"}], keyPoints: ["3x+2y=12, x−y=1: x=y+1→3(y+1)+2y=12→y=1.8","y=x², y=x+2: x²=x+2→(x−2)(x+1)=0→x=2 or −1","2x−5<7→x<6","x²<9→−3<x<3","Shade below y=2x+1 for y<2x+1"], difficulty: "advanced", durationMin: 45 },
    { title: "Sequences: Linear, Quadratic, Geometric", slug: "sequences-types", summary: "Find nth terms; continue sequences.", objectives: ["Linear nth term","Quadratic nth term","Geometric sequences","Sequence problems"], keyTerms: [{term:"Arithmetic",definition:"Constant difference"},{term:"Geometric",definition:"Constant ratio"},{term:"nth term",definition:"Formula for position n"},{term:"Common difference",definition:"Added between terms"}], keyPoints: ["3,7,11,15...: 4n−1","2,5,10,17: n²+1","3,6,12,24: 3×2^(n-1)","Fibonacci: each = sum of previous 2","Quadratic: 2nd difference constant"], difficulty: "advanced", durationMin: 45 },
    { title: "Circle Theorems", slug: "circle-theorems", summary: "Angles in circles; tangent, chord, arc properties.", objectives: ["Angle at centre","Semicircle","Cyclic quadrilateral","Multi-step"], keyTerms: [{term:"Radius",definition:"Centre to circumference"},{term:"Chord",definition:"Joining 2 circumference points"},{term:"Tangent",definition:"Touches at 1 point, ⊥ radius"},{term:"Cyclic quadrilateral",definition:"4 vertices on circle"}], keyPoints: ["Centre angle = 2× circumference angle","Semicircle angle = 90°","Same segment = equal","Cyclic quad: opposite = 180°","Tangent ⊥ radius"], difficulty: "advanced", durationMin: 45 },
    { title: "Statistics: Averages & Diagrams", slug: "statistics-averages", summary: "Mean/median/mode/range; histograms; cumulative frequency.", objectives: ["Averages from tables","Histograms","Cumulative frequency","Quartiles/IQR"], keyTerms: [{term:"IQR",definition:"Q3−Q1"},{term:"Histogram",definition:"Area = frequency"},{term:"Cumulative frequency",definition:"Running total"},{term:"Frequency density",definition:"Freq ÷ width"}], keyPoints: ["Mean from table: Σ(fx)/Σf","Median: n/2th value","IQR = Q3−Q1","Histogram: freq density on y","Cum freq: plot vs upper boundary"], difficulty: "core", durationMin: 40 },
    { title: "Probability: Conditional & Venn", slug: "probability-conditional-venn", summary: "Venn diagrams; set notation; conditional probability.", objectives: ["Venn diagrams","Set notation (∪, ∩, ')","Conditional probability","Two-way tables"], keyTerms: [{term:"Union (∪)",definition:"A or B or both"},{term:"Intersection (∩)",definition:"Both A and B"},{term:"Conditional P(A|B)",definition:"A given B"},{term:"Complement (A')",definition:"Not A"}], keyPoints: ["P(A∪B) = P(A)+P(B)−P(A∩B)","P(A|B) = P(A∩B)/P(B)","Venn: fill from inside out","P(A') = 1−P(A)","Two-way table: rows×columns"], difficulty: "advanced", durationMin: 40 },
  ]},
  { grade: 10, topics: [
    { title: "Advanced Quadratics & Discriminant", slug: "advanced-quadratics", summary: "Complex quadratics; discriminant; inequalities; transformations.", objectives: ["All solving methods","Discriminant nature of roots","Quadratic inequalities","Transform graphs"], keyTerms: [{term:"Discriminant",definition:"Δ=b²−4ac"},{term:"Completing square",definition:"a(x+p)²+q"},{term:"Quadratic inequality",definition:"x²+x−6>0"},{term:"Transformation",definition:"Translation/reflection/stretch"}], keyPoints: ["Δ>0: 2 roots; Δ=0: 1; Δ<0: 0","2x²+8x+5 = 2(x+2)²−3","x²−x−6>0: roots −2,3 → x<−2 or x>3","Translate y=x² by (3,−2): y=(x−3)²−2","Stretch: y=2x²"], difficulty: "advanced", durationMin: 50 },
    { title: "Sine & Cosine Rules", slug: "sine-cosine-rules", summary: "Non-right triangles; area formula.", objectives: ["Sine rule","Cosine rule","Area ½ab sin C","3D trigonometry"], keyTerms: [{term:"Sine rule",definition:"a/sinA = b/sinB = c/sinC"},{term:"Cosine rule",definition:"a²=b²+c²−2bc cosA"},{term:"Ambiguous case",definition:"Two possible angles"},{term:"Area formula",definition:"½ab sin C"}], keyPoints: ["Sine rule: side + opposite angle","Cosine: 3 sides or 2 sides + included angle","cosA=(b²+c²−a²)/2bc","Area = ½ab sinC","Check acute/obtuse"], difficulty: "advanced", durationMin: 50 },
    { title: "Vectors & Geometry", slug: "vectors-geometry", summary: "Column vectors; add/subtract/multiply; geometric proofs.", objectives: ["Add/subtract vectors","Scalar multiply","Magnitude","Prove with vectors"], keyTerms: [{term:"Vector",definition:"Magnitude + direction"},{term:"Scalar",definition:"Single number"},{term:"Magnitude",definition:"|v|=√(x²+y²)"},{term:"Parallel",definition:"Scalar multiple"}], keyPoints: ["|(3,4)|=5","(2,3)+(4,1)=(6,4)","3×(2,5)=(6,15)","AB=3CD → AB∥CD","Midpoint = (a+b)/2"], difficulty: "advanced", durationMin: 45 },
    { title: "Algebraic Fractions & Functions", slug: "algebra-fractions-functions", summary: "Simplify; solve; composite/inverse functions.", objectives: ["Simplify algebraic fractions","Four operations with fractions","f(x) notation","Composite/inverse"], keyTerms: [{term:"Algebraic fraction",definition:"Algebra in num/denom"},{term:"f(x)",definition:"Function mapping"},{term:"Composite fg(x)",definition:"f(g(x))"},{term:"Inverse f⁻¹",definition:"Undoes f"}], keyPoints: ["(x²−9)/(x+3)=x−3","1/x+1/(x+1)=(2x+1)/(x²+x)","f(x)=3x+2→f(5)=17","fg(x)=(x+1)² if f=x²,g=x+1","f⁻¹(17)=5 if f(x)=3x+2"], difficulty: "advanced", durationMin: 50 },
    { title: "Exponentials & Logarithms", slug: "exponentials-logarithms", summary: "Exp functions; log laws; exp equations; growth/decay.", objectives: ["y=aˣ","Log laws","Solve exp equations","Model growth/decay"], keyTerms: [{term:"Exponential",definition:"y=aˣ"},{term:"Logarithm",definition:"logₐ(x)=n means aⁿ=x"},{term:"ln",definition:"log base e"},{term:"Growth model",definition:"y=a×bˣ"}], keyPoints: ["log₂8=3 (2³=8)","log(xy)=log x+log y","log(x/y)=log x−log y","log(xⁿ)=n log x","3ˣ=81→x=4","P=1000×1.05ᵗ"], difficulty: "advanced", durationMin: 50 },
    { title: "Trig Graphs & Equations", slug: "trig-graphs-equations", summary: "Sketch sin/cos/tan; solve trig equations; identities.", objectives: ["Sketch sin/cos/tan","Amplitude/period/transform","Solve in degrees/radians","Trig identities"], keyTerms: [{term:"Amplitude",definition:"Half max-min"},{term:"Period",definition:"One cycle"},{term:"Radian",definition:"2π=360°"},{term:"Identity",definition:"sin²θ+cos²θ=1"}], keyPoints: ["sin: amp 1, period 360°, starts 0","cos: amp 1, period 360°, starts 1","tan: period 180°","y=3sin(2x): amp 3, period 180°","sin²θ+cos²θ=1","sin x=0.5: x=30° or 150°"], difficulty: "advanced", durationMin: 50 },
    { title: "Volume & Surface Area of Solids", slug: "volume-surface-solids", summary: "Cylinders, cones, spheres, pyramids.", objectives: ["Cylinder V/SA","Cone/sphere V/SA","Pyramid V","Complex 3D"], keyTerms: [{term:"Cylinder",definition:"Circular prism"},{term:"Cone",definition:"Circular base to point"},{term:"Sphere",definition:"All equidistant from centre"},{term:"Hemisphere",definition:"Half sphere"}], keyPoints: ["Cylinder: V=πr²h, SA=2πr²+2πrh","Cone: V=⅓πr²h, SA=πr²+πrl","Sphere: V=4/3πr³, SA=4πr²","Hemisphere: V=2/3πr³","Pyramid: V=⅓×base×h"], difficulty: "advanced", durationMin: 45 },
    { title: "Direct & Inverse Proportion", slug: "direct-inverse-proportion", summary: "y=kx and y=k/x; constants; graphs.", objectives: ["Direct y=kx","Inverse y=k/x","Find k","Proportion problems"], keyTerms: [{term:"Direct",definition:"y=kx"},{term:"Inverse",definition:"y=k/x"},{term:"k",definition:"Constant of proportionality"},{term:"∝",definition:"Proportional to"}], keyPoints: ["Direct: straight line through origin","Inverse: hyperbola curve","y∝x, y=10 when x=2: k=5, y=5x","y∝1/x, y=4 when x=3: k=12, y=12/x","y∝x²: y=kx²"], difficulty: "advanced", durationMin: 45 },
  ]},
  { grade: 11, topics: [
    { title: "Differentiation: Rules & Applications", slug: "differentiation-rules", summary: "Power rule; tangents/normals; turning points.", objectives: ["Power rule","Gradient at point","Tangents/normals","Turning points"], keyTerms: [{term:"Derivative f'(x)",definition:"Gradient function"},{term:"Power rule",definition:"d/dx(xⁿ)=nxⁿ⁻¹"},{term:"Tangent",definition:"Touches at 1 point"},{term:"Turning point",definition:"f'(x)=0"}], keyPoints: ["d/dx(x³)=3x²","d/dx(5x⁴)=20x³","Tangent: y−f(a)=f'(a)(x−a)","TP: f'(x)=0","f''>0 min, f''<0 max"], difficulty: "advanced", durationMin: 50 },
    { title: "Integration & Areas", slug: "integration-areas", summary: "Power rule; definite integrals; area under curves.", objectives: ["Integrate polynomials","Definite integrals","Area under curve","Area between curves"], keyTerms: [{term:"Integral ∫",definition:"Reverse of differentiation"},{term:"Definite",definition:"With limits"},{term:"Indefinite",definition:"+C"},{term:"Limits",definition:"a to b"}], keyPoints: ["∫xⁿ dx=xⁿ⁺¹/(n+1)+C","∫3x² dx=x³+C","∫₀²(x²+1)dx=[x³/3+x]₀²=8/3+2=14/3","Area=∫ₐᵇf(x)dx","Below axis: area=−∫"], difficulty: "advanced", durationMin: 50 },
    { title: "Binomial Expansion", slug: "binomial-expansion", summary: "(a+bx)ⁿ; specific terms; Pascals triangle.", objectives: ["Binomial theorem","Find specific terms","Pascals triangle","Approximations"], keyTerms: [{term:"Binomial theorem",definition:"(a+b)ⁿ=ΣC(n,k)aⁿ⁻ᵏbᵏ"},{term:"C(n,r)",definition:"n! / (r! times (n-r)!)"},{term:"Pascals triangle",definition:"1; 1,1; 1,2,1 and so on"},{term:"n factorial",definition:"n times (n-1) down to 1"}], keyPoints: ["(a+b)²=a²+2ab+b² (1,2,1)","(a+b)³=a³+3a²b+3ab²+b³ (1,3,3,1)","(a+b)⁴: 1,4,6,4,1","C(6,2)=15","(1+x)⁵=1+5x+10x²+10x³+5x⁴+x⁵"], difficulty: "advanced", durationMin: 45 },
    { title: "Trig Identities & Equations", slug: "trig-identities-equations", summary: "Pythagorean identities; double angle; radians.", objectives: ["sin²+cos²=1","Double angle","Solve in radians","Quadratic trig"], keyTerms: [{term:"Pythagorean",definition:"sin²θ+cos²θ=1"},{term:"Double angle",definition:"sin2θ=2sinθcosθ"},{term:"Radian",definition:"π=180°"},{term:"Principal values",definition:"Main solutions"}], keyPoints: ["sin²θ=1−cos²θ","sin2θ=2sinθcosθ","cos2θ=1−2sin²θ","sin x=0.5, 0≤x≤2π: x=π/6 or 5π/6","2cos²x−1=0: x=π/4,3π/4,5π/4,7π/4"], difficulty: "advanced", durationMin: 50 },
    { title: "Exponential Models & Logs", slug: "exp-models-logs", summary: "eˣ and ln; continuous growth; half-life.", objectives: ["eˣ and ln","Convert forms","Solve with logs","Continuous compounding"], keyTerms: [{term:"e",definition:"≈2.71828"},{term:"ln",definition:"log base e"},{term:"Continuous growth",definition:"y=aeᵏᵗ"},{term:"Half-life",definition:"ln(2)/k"}], keyPoints: ["logₐ(x)=y ⟺ aʸ=x","ln(e)=1, ln(1)=0","eˣ and ln(x) inverse","Growth: P=P₀eᵏᵗ","Half-life: ln(2)/k"], difficulty: "advanced", durationMin: 50 },
    { title: "Kinematics: SUVAT & Calculus", slug: "kinematics-suvat", summary: "SUVAT; calculus for motion; v-t graphs.", objectives: ["SUVAT equations","Differentiate for v","Integrate for s","v-t graphs"], keyTerms: [{term:"Displacement (s)",definition:"Distance in direction"},{term:"Velocity (v)",definition:"ds/dt"},{term:"Acceleration (a)",definition:"dv/dt"},{term:"SUVAT",definition:"Constant accel equations"}], keyPoints: ["v=u+at","s=ut+½at²","v²=u²+2as","s=½(u+v)t","s=t³−6t²+9t→v=3t²−12t+9→a=6t−12"], difficulty: "advanced", durationMin: 50 },
    { title: "Coordinate Geometry: Circles", slug: "coordinate-circles", summary: "Lines and circles; intersections; tangents.", objectives: ["Line from 2 points","Circle equation","Intersections","Perpendicular bisector"], keyTerms: [{term:"Circle equation",definition:"(x−a)²+(y−b)²=r²"},{term:"Perp bisector",definition:"90° to midpoint"},{term:"Tangent",definition:"⊥ to radius"},{term:"Discriminant test",definition:"Intersection check"}], keyPoints: ["Line through 2 points: (y−y₁)/(y₂−y₁)=(x−x₁)/(x₂−x₁)","(x−3)²+(y+2)²=25: centre(3,−2),r=5","Substitute line into circle, solve quadratic","Δ>0: 2 intersections; Δ=0: tangent; Δ<0: miss"], difficulty: "advanced", durationMin: 45 },
    { title: "Distributions & Sampling", slug: "distributions-sampling", summary: "Sampling; binomial/normal; confidence intervals.", objectives: ["Sampling methods","Binomial distribution","Normal distribution","Confidence intervals"], keyTerms: [{term:"Random sample",definition:"Equal chance"},{term:"Binomial",definition:"Successes in n trials"},{term:"Normal",definition:"Bell curve"},{term:"Confidence interval",definition:"Range for parameter"}], keyPoints: ["P(X=r)=C(n,r)pʳ(1−p)ⁿ⁻ʳ","68% within 1σ, 95% within 2σ","P(2 heads in 3)=3×0.125=0.375","z=(x−μ)/σ","95% CI: x̄±1.96σ/√n"], difficulty: "advanced", durationMin: 50 },
  ]},
  { grade: 12, topics: [
    { title: "Chain, Product & Quotient Rules", slug: "chain-product-quotient", summary: "Advanced differentiation; implicit.", objectives: ["Chain rule","Product rule","Quotient rule","Implicit"], keyTerms: [{term:"Chain",definition:"f'(g(x))×g'(x)"},{term:"Product",definition:"uv'+vu'"},{term:"Quotient",definition:"(vu'−uv')/v²"},{term:"Implicit",definition:"Differentiate both sides"}], keyPoints: ["d/dx(x²+1)³=6x(x²+1)²","d/dx(x²sinx)=x²cosx+2xsinx","d/dx(x/(x+1))=1/(x+1)²","d/dx(sinx)=cosx, d/dx(eˣ)=eˣ","x²+y²=25→dy/dx=−x/y"], difficulty: "advanced", durationMin: 55 },
    { title: "Integration Techniques", slug: "integration-techniques", summary: "Substitution; by parts; volumes of revolution.", objectives: ["Substitution","By parts","Trig/exp integrate","Volumes"], keyTerms: [{term:"Substitution",definition:"Replace variable"},{term:"By parts",definition:"∫u dv=uv−∫v du"},{term:"Volume revolution",definition:"π∫y² dx"},{term:"Partial fractions",definition:"Split fraction"}], keyPoints: ["∫2x(x²+1)³ dx: u=x²+1→(x²+1)⁴/4+C","∫xeˣ dx=xeˣ−eˣ+C","∫sinx=−cosx, ∫eˣ=eˣ","∫1/x=ln|x|","V=π∫y² dx"], difficulty: "advanced", durationMin: 55 },
    { title: "Differential Equations", slug: "differential-equations", summary: "First-order ODEs; separation; modelling.", objectives: ["Separation of variables","Particular solutions","Growth/decay models","Solution curves"], keyTerms: [{term:"ODE",definition:"dy/dx=ky"},{term:"Separation",definition:"y terms one side, x other"},{term:"Particular solution",definition:"With initial condition"},{term:"General solution",definition:"+C family"}], keyPoints: ["dy/dx=ky→y=Aeᵏˣ","y(0)=100→A=100→y=100eᵏˣ","dy/dx=2x→y=x²+C","dy/dx=x/y→y²=x²+C'","dP/dt=kP models growth"], difficulty: "advanced", durationMin: 55 },
    { title: "Complex Numbers", slug: "complex-numbers", summary: "a+bi; operations; Argand diagrams; polar form.", objectives: ["i=√(−1), a+bi","Add/subtract/multiply/divide","Modulus/argument","Argand diagrams"], keyTerms: [{term:"i",definition:"√(−1), i²=−1"},{term:"z=a+bi",definition:"a real, b imaginary"},{term:"|z|",definition:"√(a²+b²)"},{term:"arg z",definition:"Angle from real axis"}], keyPoints: ["(2+3i)+(1+4i)=3+7i","(2+3i)(1+4i)=−10+11i","|3+4i|=5","arg(3+4i)=arctan(4/3)≈53°","z=r(cosθ+i sinθ)=re^(iθ)"], difficulty: "advanced", durationMin: 55 },
    { title: "Matrices & Transformations", slug: "matrices-transformations", summary: "Matrix operations; determinant; inverse; transformations.", objectives: ["Matrix operations","det and inverse","Transformation matrices","Solve with matrices"], keyTerms: [{term:"Matrix",definition:"Rows and columns"},{term:"Determinant",definition:"ad−bc for 2×2"},{term:"Inverse A⁻¹",definition:"AA⁻¹=I"},{term:"Identity I",definition:"1s diagonal, 0s else"}], keyPoints: ["[[a,b],[c,d]]×[[e,f],[g,h]]=[[ae+bg,af+bh],[ce+dg,cf+dh]]","det[[3,1],[2,4]]=10","A⁻¹=(1/det)[[d,−b],[−c,a]]","Inverse exists if det≠0","Rotation: [[cosθ,−sinθ],[sinθ,cosθ]]"], difficulty: "advanced", durationMin: 55 },
    { title: "Numerical Methods", slug: "numerical-methods", summary: "Iteration; trapezium rule; Newton-Raphson.", objectives: ["Iteration","Trapezium rule","Newton-Raphson","Limitations"], keyTerms: [{term:"Iteration",definition:"Improving approximations"},{term:"Trapezium rule",definition:"Trapeziums for area"},{term:"Newton-Raphson",definition:"xₙ₊₁=xₙ−f(xₙ)/f'(xₙ)"},{term:"Convergence",definition:"Approaches true value"}], keyPoints: ["Trapezium: ½h(y₀+2y₁+...+yₙ)","Newton-Raphson: xₙ₊₁=xₙ−f(xₙ)/f'(xₙ)","x³−2x−5=0, x₀=2: x₁=2.1","Converges if |g'(x)|<1","Fails if f'(xₙ)=0"], difficulty: "advanced", durationMin: 55 },
    { title: "Hypothesis Testing", slug: "hypothesis-testing", summary: "Null/alternative; p-values; critical regions.", objectives: ["H₀ and H₁","Test statistics","p-values/critical regions","Interpret"], keyTerms: [{term:"H₀",definition:"Null hypothesis"},{term:"H₁",definition:"Alternative"},{term:"p-value",definition:"P(result if H₀ true)"},{term:"α",definition:"Significance level"}], keyPoints: ["H₀: μ=10, H₁: μ>10","Reject if p<α","p<0.05 significant","Type I: reject true H₀","Type II: fail to reject false H₀"], difficulty: "advanced", durationMin: 55 },
    { title: "Projectiles & 3D Vectors", slug: "projectiles-3d-vectors", summary: "Projectile motion; 3D vectors; inclined planes.", objectives: ["Projectile horizontal/vertical","3D vectors","Inclined planes","Calculus in 3D"], keyTerms: [{term:"Projectile",definition:"Under gravity, no air resistance"},{term:"3D vector",definition:"(x,y,z)"},{term:"Time of flight",definition:"Total air time"},{term:"Range",definition:"Horizontal distance"}], keyPoints: ["Horizontal: constant velocity","Vertical: a=−g=−9.8","T=2u sinθ/g","R=u²sin(2θ)/g","Max range at 45°"], difficulty: "advanced", durationMin: 55 },
  ]},
];
